site_name: love work,love life!
repo_url: https://github.com/wygfzren603/love_work_love_life.git
theme:
  # name: 'mkdocs'
  name: 'material'

markdown_extensions:
# 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  # - pymdownx.arithmatex:
  #   generic: true
  # # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  # - pymdownx.emoji:
  #   emoji_index: !!python/name:materialx.emoji.twemoji
  #   emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
    - Home: index.md
    - c/c++:
      - Guideline: cplusplus/programming_guideline.md
    - deeplearning:
      - CNN Attention: deeplearning/cnn_attention.md
      - Model Distillation: deeplearning/model_distillation.md
      - Model Quantization: deeplearning/model_quantization.md
      - Object Detection: deeplearning/object_detection.md
